name: Dev build and deploy
on:
  push:
    branches:
      - master
      - add-dev-build-deploy
  workflow_dispatch:
concurrency: ci-${{ github.ref }}
jobs:
  set-refs:
    name: Set references
    runs-on: ubuntu-latest
    steps:
      - id: set-refs
        name: Set refs
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT
      - name: Check refs
        run: |
          echo "branch: ${{ steps.set-refs.outputs.branch }}" >> $GITHUB_STEP_SUMMARY
    outputs:
      branch: ${{ steps.set-refs.outputs.branch }}
  build-and-deploy:
    environment: dev
    name: Build and deploy
    runs-on: ubuntu-latest
    needs:
      - set-refs
    steps:
      - uses: actions/checkout@v3
      - name: Check refs
        run: |
          echo "branch: ${{ needs.set-refs.outputs.branch }}"
      - uses: actions/cache@v3
        with:
          path: |
            ${{ runner.OS }}/docker
          key: ${{ runner.OS }}-docker-${{ hashFiles('**/Dockerfile') }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.OS }}-docker-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: vector623
          password: ${{ secrets.GHCR_GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: ghcr.io/ptcdevs/python-restapi:${{ needs.set-refs.outputs.branch }}
          push: true
      - name: Output image tag
        run: |
          echo "docker tag: ghcr.io/ptcdevs/python-restapi:${{ needs.set-refs.outputs.branch }}" >> $GITHUB_STEP_SUMMARY